name: Sync Upstream

on:
  schedule:
    # 每天 UTC 00:00 (北京时间 08:00) 自动执行
    - cron: '0 0 * * *'
  workflow_dispatch: # 支持在 Actions 页面手动点击执行

jobs:
  sync-latest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Sync with upstream repository
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 如同步其他分支，将 master 改为对应分支名即可
          gh repo sync ${{ github.repository }} -b master
